# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          USERNAME: ${{ secrets.CFL_DOCKER_USERNAME }}
        run: echo "Logging in as $USERNAME"
      - name: Login to CoreFiling docker
        uses: docker/login-action@v1
        with:
          registry: docker.corefiling.com
          username: ${{ secrets.CFL_DOCKER_USERNAME }}
          password: ${{ secrets.CFL_DOCKER_PASSWORD }}
